### ISSUE TITLE
Rüstungsständer, Gemälde und Rahmen abbauen

### ISSUE THREAD

**Issue by MeikeKrug** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#101]
In der Bauwelt und in der Plotwelt ist es nicht möglich Gemälde, Ramen und Rüstungsständer normal ab zu bauen. Bei Ramen und Gemälden kann man nur den Block hinten dran entfernen und damit das Gemälde oder den Ramen droppen lassen und beim Rüstungsständer muss man mit Lava arbeiten. Das ist etwas unpraktisch. Es wäre schön wenn man diese Gegenstände auch so abbauen könnte, ohne diese Tricks, da jetzt nicht unbedingt jeder darauf kommt.

**Comment by Tigerpanzer02** [comment]
@MeikeKrug Danke für die Meldung des Bugs. Der Bug wurder erfolgreich auf der Bauwelt & Plotwelt behoben!

Wir wünschen weiterhin viel Spaß auf CC-SW Network!

Entschuldige bitte die lange Bearbeitungszeit!
