### ISSUE TITLE
Killbefehl fehlerhaft

### ISSUE THREAD

**Issue by PrInZeSsSaRaYa** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#102]
# Leider Bugt der Kill befehl

# Zum Reproduzieren
Einstellungen:
- Service:

[] Minecraft
      - Server: Überall
      - Client/Version/Platform: 1.12.2
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges

# mit /kill sollte man ein besschen fan beibehalten 🌵 

# Screenshots

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows, Linux]

**Sonstiges**

Das finde ich schade das mods das nicht mehr können ich hoffe es ist nur ein bug

**Comment by Tigerpanzer02** [comment]
Behoben
