### ISSUE TITLE
Belohnungsmanager und Villanger im Einkaufszentrum (Bauwelt) bug

### ISSUE THREAD

**Issue by lpschmalexYT** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#103]
# Beschreibung
Die Villanger in der Bauwelt lassen sich nicht anklicken, bzw es kommt eine Nachricht, dass ich einen Augenblick warten soll. Bei dem Belohnungsmanager in der Lobby ist es so, dass er ein normaler Villanger ist (Kathograf).

# Zum Reproduzieren
Einstellungen:
- Service:

[x] Minecraft
      - Server: Bauwelt und Lobby
      - Client/Version/Platform:
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges

# Was sollte passieren?
Es wäre schön, wenn man den Bug beheben könnte oder ein /vote Plugin geben würde.

# Screenshots

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows, Linux]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
Wurde behoben...
