### ISSUE TITLE
kleiner Teamspeakrechtschreibfehler

### ISSUE THREAD

**Issue by TheButtabrotTV** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#24]
**Beschreibung**
Eine kurze Erklärung um den Fall zu verstehen

**Was sollte passieren eigentlich**
Rechtschreibfehler beheben

**Screenshots**
https://gyazo.com/600650122dcc7fdd80656c9655d11d12

**Sonstiges**

Es hat sich ein kleiner Fehler eingeschlichen... https://gyazo.com/600650122dcc7fdd80656c9655d11d12 Wenn die Zeit vorhanden ist bitte ich dies zu beheben. LG Adminleitung / Zukunftsserveradmin XD

**Comment by Tigerpanzer02** [comment]
Danke ;)
Hab die Nachricht angepasst...
