### ISSUE TITLE
Minecraft: Bedwars - Map:Clash Royale

### ISSUE THREAD

**Issue by TigerDragoner** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#31]
**Beschreibung**

Auf der Map Clash Royale spawnt kein Eisen oder Bronze und auch kein Gold ausserdem wird man erst in die runde teleportiert wenn man es geschaft hat sich in der wartelobby zu töten
 **Zum Reproduzieren**
Einstellungen / Entscheidungen die du hattest:

- Service: Minecraft 
- Server: BW-? 
- Client/Version/Platform: 1.8.9 Minecraft  Windows 

**Was sollte passieren eigentlich**
 Das man in die map tp wird wenns losgeht und das die Sachen halt spawnen

**Minecraft (please complete the following information):**
 - Client: [e.g. Minecraft Launcher] 1.8.9
 - Version:[e.g. 1.8,1.12] 1.8.9

**Comment by TigerDragoner** [comment]
Also in der Bedwars map Clash Royale

**Comment by Tigerpanzer02** [comment]
Gerade getestet - Funktioniert einwandfrei

**Comment by Tigerpanzer02** [comment]
Könntest du bitte nochmal schauen? Bzw was dazu beitragen, warum es nicht geht
