### ISSUE TITLE
Minecraft: GetDown

### ISSUE THREAD

**Issue by xXNisekoiXx** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#48]
# Beschreibung
Normale User ohne speziellen rang können kein getdown spielen sie spawnen in einer flat world und wenn sie sterben auch wieder in einer flat world

# Zum Reproduzieren
Einstellungen / Entscheidungen die du hattest:
- Service:
[X] Minecraft
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges
- Server: GetDown-1
- Client/Version/Platform: 1.8.8

**Comment by Tigerpanzer02** [comment]
Nach Test konnten wir leider diesen Fehler nicht finden

**Comment by Tigerpanzer02** [comment]
Nach dem du keine Antwort gibst schließen wir diesen Fall. Falls du der Meinung bist er existiert oder du möchtest nochmals informationen geben, dann öffne diesen Issue erneut
