### ISSUE TITLE
S-Admin Commands

### ISSUE THREAD

**Issue by Ristbo** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#52]
# Beschreibung

Bei dem  S-Admin Rang funktionieren nicht alle Commands, man bekommt die Meldung das man die Rechte dazu Nicht hat.
# Zum Reproduzieren
Einstellungen / Entscheidungen die du hattest:
- Service:
[x] Minecraft
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges
- Server:
- Client/Version/Platform:1.12.2

# Was sollte passieren?

# Screenshots

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows, Linux]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Samsung S8]
 - OS: [e.g. iOS8.1, Android 7]
 - Browser [e.g. stock browser, safari, google chrome]

**Minecraft (please complete the following information):**
 - Client: [e.g. Minecraft Launcher, Labymod]
 - Version:[e.g. 1.8,1.12]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
Was bedeutet für dich nicht alle Commands?

**Comment by Ristbo** [comment]
Npc und ban liste,mehr haben wir bis jetzt noch nicht rausgefunden

**Comment by Tigerpanzer02** [comment]
Banliste inwiefern?

**Comment by Tigerpanzer02** [comment]
Es gibt kein befehl für eine Banliste... Oder was ist damit gemeint?

**Comment by Tigerpanzer02** [comment]
Npc sollten nun gehen! BanListe gibt es nicht...
Sonst noch etwas?

**Comment by Ristbo** [comment]
Bis jetzt nicht werde dir aber noch ein Screenshot zu diesem Team senden

**Comment by Tigerpanzer02** [comment]
Somit ist es für mich erledigt. Falls noch was offen steht, dann öffne den Issue erneut
