### ISSUE TITLE
Minecraft: DrawMyThing

### ISSUE THREAD

**Issue by Ristbo** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#53]
# Beschreibung

DrawMyThing startet nicht richtig 

 Minecraft

- Client/Version/Platform:1.12.2

**Comment by Tigerpanzer02** [comment]
Kannst du mir bitte noch Server, Datum und Uhrzeit geben? Damit ich in den Logs nach Fehlern suchen kann. Danke

**Comment by Ristbo** [comment]
Muss ich schauen hab vllt sogar einen Screenshot gemacht

**Comment by Ristbo** [comment]
![2018-08-15_16 39 09](https://user-images.githubusercontent.com/38503816/44528074-f2be9580-a6e8-11e8-9d44-9f8369205ac9.png)

**Comment by Ristbo** [comment]
15.08.18 um 16:39 Uhr und 9 Sekunden

**Comment by Tigerpanzer02** [comment]
Wurde erfolgreich mit dem neusten Update gefixt! Viel Spaß
