### ISSUE TITLE
Minecraft: GetDown

### ISSUE THREAD

**Issue by xXNisekoiXx** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#54]
# Beschreibung

# Zum Reproduzieren
Einstellungen / Entscheidungen die du hattest:
- Service:
[x] Minecraft
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges
- Server: mc.cc-sw.de ### Hier sollte der Server stehen bsp. GetDown-1
- Client/Version/Platform: minecraft 1.8.9 | Labymod3.2.9

# Was sollte passieren?

Wenn man mit Mods oder anderen spieler die keinen rang haben GetDown spielen will Funktioniert das nicht da sie in einer Survival Map Spawnen anstatt in der vorgesehenen Lobby und sie haben keine Items wie z.b das Buch um die Maps zu wählen so wie das man die Kits wählen kann funktioniert bei anderen Spielern nicht . Außer es handelt sich um Admins, S-Admins, Co-Owner und Ownerin da funktionieren alle Features die es in dem Gamemode gibt. 

# Screenshots

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows10, Linux]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Samsung S8]
 - OS: [e.g. iOS8.1, Android 7]
 - Browser [e.g. stock browser, safari, google chrome]

**Minecraft (please complete the following information):**
 - Client: [e.g. Minecraft Launcher, Labymod]
 - Version:[e.g. 1.8,1.12]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
Dieser Fehler ist schwierig zum reproduzieren...
Kannst du mir bitte noch Server, Datum und Uhrzeit geben? Damit ich in den Logs nach Fehlern suchen kann. Danke

**Comment by Tigerpanzer02** [comment]
Wahrscheinlich kommt dieser Fehler auch bei Baukampf...

**Comment by Ristbo** [comment]
Ja gelegentlich schon

**Comment by Tigerpanzer02** [comment]
Am besten demnächst wenn das Problem nochmal auftritt mit Datum und Uhrzeit hier melden! Danke im Voraus

**Comment by Tigerpanzer02** [comment]
MySQL Utils Fehler. Bug Reportet

**Comment by Tigerpanzer02** [comment]
Fehler wurde in Baukampf behoben

**Comment by Tigerpanzer02** [comment]
Nun auch in Getdown
