### ISSUE TITLE
Minecraft-Dorfverteidigung 

### ISSUE THREAD

**Issue by Ristbo** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#55]
# Beschreibung

Der Server lagt ab einer bestimmten anzahl von Zombies zudem wird man vom anti cheat gekickt und vom Server selbst durch die Lags gekickt 
# Zum Reproduzieren
Einstellungen / Entscheidungen die du hattest:
- Service:
[x] Minecraft
![2018-08-27_17 21 04](https://user-images.githubusercontent.com/38503816/44668670-549b3a00-aa1e-11e8-94a5-56901d92546f.png)

**Comment by Tigerpanzer02** [comment]
Mehr Ram zugewiesen. AntiCheat temporär verändert. Nach dem nächsten großen Server Neustart sollte es behoben sein.
