### ISSUE TITLE
Bewerbungseite 

### ISSUE THREAD

**Issue by Ristbo** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#60]
Bei der Ersten Überschrift  ist der Obere Kasten noch in der Überschrift.
Bei der Zweiten Überschrift ist diese nicht  und wird so weiter rechts angezeigt.
![screenshot 1](https://user-images.githubusercontent.com/38503816/47254955-36bfe380-d469-11e8-88e5-d18356222f04.png)
![screenshot 2](https://user-images.githubusercontent.com/38503816/47254956-3aec0100-d469-11e8-81f3-219841427433.png)

**Comment by Tigerpanzer02** [comment]
Bewerbungseite vollständig optimiert
