### ISSUE TITLE
Website Schreibfehler 

### ISSUE THREAD

**Issue by Ristbo** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#66]
Spedition Mitglieder und Fuhrpark:
Bei Tigerpanzer ist das wort"Kennzeichen" falsch geschrieben

Speditionsfahrer Name falsch: TimspieltHD

Dann ist Das Wort Auszubildende bei der Überschrift falsch geschrieben bei Spedition

Dann bei der Seite Spedition Bewerbung ist unten das Wort Fahrer falsch geschrieben

**Comment by Tigerpanzer02** [comment]
Falls Ihnen weitere Fehler auffallen ->  Öffnen Sie einfach wieder diesen Issue
