### ISSUE TITLE
Website Schreibfehler

### ISSUE THREAD

**Issue by Ristbo** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#67]
Bei Speditionsteam ganz unten bei Auszubildende/r falsch geschrieben.
Bei Spedition&Jobs, bei Fahrer steht den LKW ich finde da mus dem LKW.Können wir auch gern nochmal drüber reden 2x

**Comment by Tigerpanzer02** [comment]
Was ist bei Auszubildende falsch geschrieben?
