### ISSUE TITLE
Belohnungsbug Minecraft

### ISSUE THREAD

**Issue by lpschmalexYT** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#81]
Man kann die Premium Silber Blohnungen und die Premium Gold Belohnungen als Moderator nicht abholen. Allerdings als Admin schon

# Beschreibung

# Zum Reproduzieren
Einstellungen / Entscheidungen die du hattest:
- Service:
[x] Minecraft
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges
- Server:
- Client/Version/Platform:

# Was sollte passieren?
Man sollte als Teammitglied die Belohnungen bekommen, da man ja höher als ein Spieler (im Rang) ist. Allerdings ist dies erst ab dem Rang Admin der fall.  

# Screenshots

**Desktop (please complete the following information):**
 Windows 10- OS/System: [e.g. iOS, Windows, Linux]

**Minecraft (please complete the following information):**
 Minecraft Launcher- Client: [e.g. Minecraft Launcher, Labymod]
 Version 1.12.2- Version:[e.g. 1.8,1.12]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
Danke für die Anfrage:
- Es ist kein wirklicher Bug
- Es wurde bereits für Moderatoren die benötigten Gruppen hinzugefügt
Wir hoffen das somit der Issue geschlossen werden kann. Falls Sie noch weitere Probleme haben öffnen sie einfach einen neuen Issue.
