### ISSUE TITLE
Minecraft Plotwelt straßen bei gemergten plots komisch

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#85]
# die ränder in der plotwelt sind bei gemergten plots komisch

#85 
Einstellungen / Entscheidungen die du hattest:
- Service:
[X] Minecraft
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges
- Server:
- Client/Version/Platform:

#

# 
![Uploading 2019-04-06_16.00.12.png…]()

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows, Linux]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Samsung S8]
 - OS: [e.g. iOS8.1, Android 7]
 - Browser [e.g. stock browser, safari, google chrome]

**Minecraft (please complete the following information):**
 - Client: [e.g. Minecraft Launcher, Labymod]
 - Version:[e.g. 1.8,1.12]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
Durch die Änderung der Straßen ist an gemergten Plots der Weg eventuell ohne Rand. Der Rang kann einfach ersetzt werden.
