### ISSUE TITLE
Server-Team-Rang Vorschlag/Rechte Erweiterung

### ISSUE THREAD

**Issue by lpschmalexYT** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#87]
Meine Anfrage bezieht sich auf kein Problem** Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.**
Ich fühle mich minderwertig, wenn ich mich nicht tpn kann. Jeder kann das außer ich. Es wäre generell nice, wenn dieser Rang sich tpn könnte, in das Reportsystem und den Teamchat einloggen könnte

** Beschreibe die Lösung, die du möchtest **
Ich möchte, dass der Rang (Team) die oben genannten Rechte bekommt.

** Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben **

** Zusätzlicher Kontext **

**Comment by Tigerpanzer02** [comment]
Guten Tag,

in einem großen Serverteam indem gewisse Leute ihre Tätigkeitsbereiche haben können nicht einfach alle diese Rechte bekommen. Das Reportsystem ist ausschließlich für den Moderator und alle weiteren Beauftragen um zu gerechtfertigen das ein genauer und fairer Umgang für alle gleich ermöglicht wird. Sicherlich lässt sich über das Thema Teamchat und eigenes Teleportieren reden.

Mit freundlichem Grüßen und die Leitungen werden sich bereden über eine allgemein Passende Möglichkeit.

**Comment by lpschmalexYT** [comment]
Guten Tag,
Vielen Dank für ihre Antwort. Ich werde informiert, wenn ihr zu einem Entschluss gekommen seid?

Mit freundlichen Grüßen
lpschmalexYT

**Comment by Tigerpanzer02** [comment]
Eigene Teleportation und Teamchat wurden freigegeben.
