### ISSUE TITLE
Minecrfat  pvp aus der map glitch

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#92]
# wen man eine enderperle (die  map mit dem dach) wirft sie noch in der luft ist und du dobbel jumb machst bist du über dere map und komst nicht mehr rein

# weitere infos folge auf ts und er wird zum testen gezeigt
Einstellungen:
- Service:

[x] Minecraft
      - Server:
      - Client/Version/Platform:
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges

# Was sollte passieren?

# Screenshots

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows, Linux]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
Dach entfernt und bug somit behoben.
