### ISSUE TITLE
draw my thing

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#93]
** Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.**
Es ist sehr schwer zu zeichnen in draw my thing wen immer das schild vor der zeichnung ist beim zeichnen das ist sehr nervig

** Beschreibe die Lösung, die du möchtest **

Schild weg!!!!!

** Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben **

** Zusätzlicher Kontext **

**Comment by Tigerpanzer02** [comment]
Client-Side Shield
Kann nichts geändert werden.

**Comment by Tigerpanzer02** [comment]
Information: Der neue Modus GuessNDraw hat dieses "Problem" gelöst!

**Comment by Tigerpanzer02** [comment]
@Viereckig Information: Der neue Modus GuessNDraw (ersetzt DrawMyThing) hat dieses "Problem" gelöst und dich wird dort kein Schild nerven ;)
