### ISSUE TITLE
Gadgets

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#94]
** Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.**
Ich habe mega viel coins ausgegeben das ich gadgeds hab und jetzt habe ich anscheinend keine berechtigungen bitte um schnelle behebung

** Beschreibe die Lösung, die du möchtest **

das ich es benutzen kann

** Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben **

** Zusätzlicher Kontext **

**Comment by Tigerpanzer02** [comment]
Fixed
