### ISSUE TITLE
Kisten

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#95]
** Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.**das mehrere Gleichzeitig Kisten öffnen können das ist nervig wen man immer warten muss wird den Spielern sicher auch nicht dan gefallen und kaufen dan keine kisten
Vorschlag das man nur selbst sieht was man mit Kisten macht und unsichtbar ist das andere auch öffnen können

** Beschreibe die Lösung, die du möchtest **

** Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben **

** Zusätzlicher Kontext **

**Comment by Tigerpanzer02** [comment]
Es werden noch weiter Standorte hinzugefügt.
