### ISSUE TITLE
Bauwelt Kisten und redstone bug und türen

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#96]
# wenn du ein paar mal hintereinander Kisten öffnest kanst du danach keine Kisten mehr öffnen und kein Redstone mehr verwenden+ türen

# du musst dann immer reconekten dass es wieder klappt
Einstellungen:
- Service:

[x] Minecraft
      - Server:
      - Client/Version/Platform:
[] Web
[] Teamspeak
[] Discord
[] Store
[] Sonstiges

# Was sollte passieren?

# Screenshots

**Desktop (please complete the following information):**
 - OS/System: [e.g. iOS, Windows, Linux]

**Sonstiges**

**Comment by Tigerpanzer02** [comment]
@Viereckig Der Fehler konnte nicht nachvollzogen werden! Wir benötigen mehr Informationen zu diesem Problem!

**Comment by Viereckig** [comment]
trit nicht mehr auf
