### ISSUE TITLE
Msg 

### ISSUE THREAD

**Issue by Viereckig** [Tigerpanzer02/CC-SW-Network---Fehler-Bugs-Probleme#98]
** Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.**also es ist nervig das mann mit einem Spieler befreundet sein muss das man mit ihm schreiben kann(/msg) oder auch z. B ohne das kann man nicht gut handeln den früher oder später Kan man nicht mehr mit einer bestimmten person über den chat schreiben und es ist doch nervig das du zuerst jedem vor dem Handeln eine Fa zu schiken um mit dem handeln zu können

** Beschreibe die Lösung, die du möchtest **

** Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben **

** Zusätzlicher Kontext **

**Comment by Tigerpanzer02** [comment]
Wäre ein reales Chat Verhalten, wie es in #97 ist zufrieden stellend? Über die Option immer msg´s zu schreiben lässt sich verhandeln.

**Comment by Tigerpanzer02** [comment]
Msg´s freigegeben...
